### ISSUE TITLE
Add support for private fields

### ISSUE THREAD

**Issue by sublayerio** [sblyr/tools#3]
Private fields should be excluded from API responses since they contain information that should only be accessible server-side.

Something like this:

```yaml
apiVersion: v1
kind: Model
spec:
  id: Event
  name: Event
  plural: Events
  collectionKey: events
  tableName: events
  clearable: true
  fields:
    - id: type
      name: Type
      type: text
      required: true
    - id: privateProp
      name: Private property
      description: This property isn't accessible in the front-end
      type: text
      private: true
```
